### ISSUE TITLE
Quirky require paths on OSX

### ISSUE THREAD

**Issue by quidquid** [openvenues/ruby_postal#1]
Hi there, this is exciting news, thanks so much for releasing your work! I'm building and trying it out on OSX, and everything is smooth up to trying out the parse/expand examples in the ruby binding. I got the gem and bundled / built the native extension, and then when I went to require it, get this: 

```
2.0.0-p353 :002 > require 'ruby_postal/expand'
LoadError: cannot load such file -- ruby_postal/cpostal/expand
    from /Users/lsheradon/.rvm/gems/ruby-2.0.0-p353@wdwot32/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
    from /Users/lsheradon/.rvm/gems/ruby-2.0.0-p353@wdwot32/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/lsheradon/.rvm/gems/ruby-2.0.0-p353@wdwot32/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/lsheradon/.rvm/gems/ruby-2.0.0-p353@wdwot32/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
    from /Users/lsheradon/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib/ruby_postal/expand.rb:1:in `<top (required)>'
```

So I did some investigating and found the cpostal directory...

```
lsheradon@Spectral:~/Sites/WDWOT (search)$ pushd /Users/lsheradon/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib/ruby_postal
~/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib/ruby_postal ~/Sites/WDWOT
lsheradon@Spectral:~/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib/ruby_postal (master)$ ls
total 24
-rw-r--r--  1 lsheradon  staff   186B Mar  3 13:59 expand.rb
-rw-r--r--  1 lsheradon  staff   263B Mar  3 14:00 parser.rb
-rw-r--r--  1 lsheradon  staff    38B Mar  3 13:33 version.rb
lsheradon@Spectral:~/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib/ruby_postal (master)$ cd ..
lsheradon@Spectral:~/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib (master)$ ls
total 8
drwxr-xr-x  4 lsheradon  staff   136B Mar  3 13:44 cpostal/
drwxr-xr-x  5 lsheradon  staff   170B Mar  3 14:00 ruby_postal/
-rw-r--r--  1 lsheradon  staff    50B Mar  3 13:33 ruby_postal.rb
lsheradon@Spectral:~/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib (master)$ ls cpostal
total 56
-rwxr-xr-x  1 lsheradon  staff    14K Mar  3 13:44 expand.bundle*
-rwxr-xr-x  1 lsheradon  staff   9.4K Mar  3 13:44 parser.bundle*
lsheradon@Spectral:~/.rvm/gems/ruby-2.0.0-p353@wdwot32/bundler/gems/ruby_postal-1625bffd903e/lib (master)$ ls ruby_postal
total 24
-rw-r--r--  1 lsheradon  staff   186B Mar  3 13:59 expand.rb
-rw-r--r--  1 lsheradon  staff   263B Mar  3 14:00 parser.rb
-rw-r--r--  1 lsheradon  staff    38B Mar  3 13:33 version.rb
```

Edited `expand.rb` to say `require cpostal/expand` and then lo and behold, `require ruby_postal/expand` succeeds. Did the same with the parser and it all works like a charm! Just thought you might like to know, this is how the build played out on my machine; not sure if it also applies to a linux environment. Thanks again,

Larry

**Comment by albarrentine** [comment]
Hey Larry - thanks for checking it out!

That is indeed odd. I also develop on OSX with that version of Ruby and haven't seen the error, but I'm no Ruby expert (beyond the C API), so may have been installing it a different way. I did notice one potential issue in extconf.rb that could be causing the install fail, namely the makefile target prefix. Would you mind pulling latest and letting me know if that fixes the install for you?

**Comment by quidquid** [comment]
Yup, updating did it, cpostal is now under lib/ruby_postal and requiring is all :100: - thanks!

**Comment by albarrentine** [comment]
Hooray!
